name: Python Test

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        name: Test Build

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up Python 3.11
          uses: actions/setup-python@v2
          with:
            python-version: 3.11

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            # pip install -r requirements.txt
            cd ~
            pwd
            mkdir -p .aws
            touch .aws/test_config

        - name: Run tests
          run: |
            pwd
            ls -al
            python -m unittest discover